- id: '1636709438820'
  alias: Restart HA
  description: Restart HA every day at 2 am
  trigger:
  - platform: time
    id: 2AM
    at: 02:00
  condition: []
  action:
  - service: hassio.host_reboot
  mode: single
- id: '1643646595675'
  alias: Notifier lumiere externe allumée
  description: Envoyer notification lorsque la lumière externe est allumée.
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: light.tz3000_5bsf8vaj_ts0505a_978ce4fe_level_light_color_on_off
  condition: []
  action:
  - service: notify.notify
    data:
      message: Lumière externe allumée
      title: Home Assistant Alert
  mode: single
- id: '1646526388783'
  alias: Poussoir Lampe Externe
  description: ''
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: 10810a52d988ea9a08902d3607d02547
      command: 'off'
  condition: []
  action:
  - type: toggle
    device_id: 855b274bfcc566eb5732df94c7cb70ef
    entity_id: light.tz3000_5bsf8vaj_ts0505a_978ce4fe_level_light_color_on_off
    domain: light
  mode: single
- id: '1647725065844'
  alias: Boutons salon
  description: Permet d'allumer les abat-jours et ventilateurs de la cheminée.
  use_blueprint:
    path: luisfmrosa/zha-ts004f-tuya-4-button-dimmer-switch-blueprint.yaml
    input:
      tuya_4button_dimmer_switch: 1c718c731f42ff34af6e967abe190630
      button_one_short_press:
      - type: toggle
        device_id: a3cc2e93d32b14c725bbcdc3e0a5fcdc
        entity_id: switch.prise_lampe_cote_cuisine_on_off
        domain: switch
      button_two_short_press:
      - type: toggle
        device_id: 1043e590b75c6cefe82ecafff45dabbc
        entity_id: switch.prise_ventilateur_cheminee_on_off
        domain: switch
      button_three_short_press:
      - type: toggle
        device_id: 0975f80d61b28078cb26002eed1a05dd
        entity_id: light.lampe_cheminee_gauche_level_light_color_on_off
        domain: light
      button_four_short_press:
      - type: toggle
        device_id: 18a1268f01529398721e4b9be262bfaf
        entity_id: light.lampe_cheminee_droite_level_light_color_on_off
        domain: light
