- id: '1636709438820'
  alias: Restart HA
  description: Restart HA every day at 2 am
  trigger:
  - platform: time
    id: 2AM
    at: 02:00
  condition: []
  action:
  - service: hassio.host_reboot
  mode: single
- id: '1643646595675'
  alias: Notifier lumiere externe allumée
  description: Envoyer notification lorsque la lumière externe est allumée.
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id:
    - light.lampe_externe_level_light_color_on_off
  condition: []
  action:
  - service: notify.notify
    data:
      message: Lumière externe allumée
      title: Home Assistant Alert
  mode: single
- id: '1649530537208'
  alias: Associer bouton cuisine lampe externe
  description: ''
  use_blueprint:
    path: apollo1220/zha-sonoff-button-press-double-press-hold-actions.yaml
    input:
      button_id: 7ff3606dd6dc00e8ad9be5208aa56ab9
      press_action:
      - type: toggle
        device_id: 855b274bfcc566eb5732df94c7cb70ef
        entity_id: light.lampe_externe_level_light_color_on_off
        domain: light
- id: '1649537188340'
  alias: Bouton vers abatjour
  description: ''
  use_blueprint:
    path: apollo1220/zha-sonoff-button-press-double-press-hold-actions.yaml
    input:
      button_id: b44d9f19aa7e7138f81e507d5a4f235e
      press_action:
      - type: toggle
        device_id: bd825139ec1d98a7cf24b782bd2a34c0
        entity_id: switch.prise_abatjour_on_off
        domain: switch
- id: '1653171943515'
  alias: Prises 4 boutons - Salon
  description: 'Automation utilisée pour allumer/éteindre:

    - Bouton 1: prise lampe côté cuisine

    - Bouton 2: lampe côté gauche cheminée

    - Bouton 3: lampe côté droite cheminée

    - Bouton 4: prise ventilateur cheminée'
  use_blueprint:
    path: luisfmrosa/zha-ts004f-tuya-4-button-dimmer-switch-blueprint.yaml
    input:
      tuya_4button_switch: 1c718c731f42ff34af6e967abe190630
      button_1_click:
      - type: toggle
        device_id: a3cc2e93d32b14c725bbcdc3e0a5fcdc
        entity_id: switch.prise_lampe_cote_cuisine_on_off
        domain: switch
      button_2_click:
      - type: toggle
        device_id: f1e7face819836455e5542cc3e9f8493
        entity_id: light.tz3000_odygigth_ts0505a_2421d6fe_level_light_color_on_off
        domain: light
      button_3_click:
      - type: toggle
        device_id: 1043e590b75c6cefe82ecafff45dabbc
        entity_id: switch.prise_ventilateur_cheminee_on_off
        domain: switch
      button_4_click:
      - type: toggle
        device_id: 1882157d5bf425efdc01f35f12f2e0ac
        entity_id: light.tz3000_dbou1ap4_ts0505a_03741bfe_level_light_color_on_off
        domain: light
- id: '1653185467799'
  alias: Read ZLinky_TIC HC + HP every minute
  description: ''
  trigger:
  - platform: time_pattern
    hours: '*'
    minutes: /1
    seconds: '0'
  condition: []
  action:
  - service: zha_toolkit.execute
    data:
      command: attr_read
      cluster: 1794
      attribute: 256
      state_id: sensor.lixee_zlinky_tic_metering_HC
      allow_create: false
      ieee: 00:15:8d:00:05:d2:99:4d
  - service: zha_toolkit.execute
    data:
      command: attr_read
      ieee: 00:15:8d:00:05:d2:99:4d
      cluster: 1794
      attribute: 258
      state_id: sensor.lixee_zlinky_tic_metering_HP
      allow_create: false
  mode: single
- id: '1654936293797'
  alias: Associer Button chaufferie lampe externe
  description: ''
  use_blueprint:
    path: apollo1220/zha-sonoff-button-press-double-press-hold-actions.yaml
    input:
      button_id: 10810a52d988ea9a08902d3607d02547
      press_action:
      - type: toggle
        device_id: 855b274bfcc566eb5732df94c7cb70ef
        entity_id: light.tz3000_5bsf8vaj_ts0505a_978ce4fe_level_light_color_on_off
        domain: light
- id: '1662222936901'
  alias: Chambre Provence - 2 buttons
  description: ''
  trigger:
  - device_id: 3ab9c428743d0b8a5c6a42a425ec26d7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
    id: Bouton.2_switches.1st_button_press
  - device_id: 3ab9c428743d0b8a5c6a42a425ec26d7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - if:
    - condition: trigger
      id: Bouton.2_switches.1st_button_press
    then:
    - type: toggle
      device_id: 1d7d7e31fc798167e1b738f78c62d888
      entity_id: switch.prise_lampe_ancienne_on_off
      domain: switch
    else:
    - type: toggle
      device_id: 57d06ece0d720e540cf89f953a317a44
      entity_id: switch.prise_ventilateur_on_off
      domain: switch
  mode: single
- id: '1662312239816'
  alias: Chaufferie - Mouvement allume lumière
  description: Si mouvement détecté, lumière s'allume pendant 1 minute.
  trigger:
  - type: motion
    platform: device
    device_id: 822d84d105e801440d1c989a04d0c6ad
    entity_id: binary_sensor.sensorpresence_iaszone
    domain: binary_sensor
    id: Chaufferie.presence.started
  - type: no_motion
    platform: device
    device_id: 822d84d105e801440d1c989a04d0c6ad
    entity_id: binary_sensor.sensorpresence_iaszone
    domain: binary_sensor
  condition: []
  action:
  - if:
    - condition: trigger
      id: Chaufferie.presence.started
    then:
    - type: turn_on
      device_id: f937b273addd94fec7ad915562ea9182
      entity_id: light.switchlampe_interne_light
      domain: light
    else:
    - type: turn_off
      device_id: f937b273addd94fec7ad915562ea9182
      entity_id: light.switchlampe_interne_light
      domain: light
  mode: single
- id: '1668031421209'
  alias: Piscine-Hors-Gel
  description: Déclanche la pompe de la piscine si la température extérieure franchit
    les seuils 1 (marche 15 min) ou 2 (marche 30 min).
  trigger:
  - platform: time_pattern
    hours: /1
  - platform: state
    entity_id: input_boolean.hors_gel_valid
    id: hg_deval
    from: 'on'
    to: 'off'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.lumi_lumi_weather_temperature_2
        below: input_number.hors_gel_inf_seuil2
      - condition: state
        entity_id: input_select.mode_fonctionnement_piscine
        state: Hiver
      - condition: state
        entity_id: input_boolean.hors_gel_valid
        state: 'on'
      sequence:
      - service: input_select.select_option
        data:
          option: Ma F
        target:
          entity_id: input_select.mode_fonctionnement_piscine
      - service: notify.notify
        data:
          message: '{{states("sensor.date_time") }}'
          title: Piscine Hors-Gel Seuil 2 Pompe Demarrée
      - delay:
          hours: 0
          minutes: 30
          seconds: 0
          milliseconds: 0
      - service: input_select.select_option
        data:
          option: Hiver
        target:
          entity_id: input_select.mode_fonctionnement_piscine
      - service: notify.notify
        data:
          title: Piscine Hors-Gel Seuil 2 Arrêt Pompe
          message: '{{states("sensor.date_time") }}'
    - conditions:
      - condition: numeric_state
        entity_id: sensor.lumi_lumi_weather_temperature_2
        below: input_number.hors_gel_inf_seuil1
      - condition: state
        entity_id: input_select.mode_fonctionnement_piscine
        state: Hiver
      - condition: state
        entity_id: input_boolean.hors_gel_valid
        state: 'on'
      sequence:
      - service: input_select.select_option
        data:
          option: Ma F
        target:
          entity_id: input_select.mode_fonctionnement_piscine
      - service: notify.notify
        data:
          title: Piscine Hors-Gel Seuil 1 Marche Pompe
          message: '{{states("sensor.date_time") }}'
      - delay:
          hours: 0
          minutes: 15
          seconds: 0
          milliseconds: 0
      - service: input_select.select_option
        data:
          option: Hiver
        target:
          entity_id: input_select.mode_fonctionnement_piscine
      - service: notify.notify
        data:
          title: Piscine Hors-Gel Seuil 1 Arrêt Pompe
          message: '{{states("sensor.date_time") }}'
    - conditions:
      - condition: trigger
        id: hg_deval
      sequence:
      - service: input_select.select_option
        data:
          option: Hiver
        target:
          entity_id: input_select.mode_fonctionnement_piscine
      - service: notify.notify
        data:
          title: Piscine Hors-Gel dévalidé
          message: '{{states("sensor.date_time") }}'
  mode: restart
  max: 10
- id: '1688076739539'
  alias: Associate switch button1-lampe_ancienne
  description: Un short press on switch.2buttons (button 1) toggles "lampe ancienne".
  trigger:
  - device_id: 3ab9c428743d0b8a5c6a42a425ec26d7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - type: toggle
    device_id: 1d7d7e31fc798167e1b738f78c62d888
    entity_id: switch.prise_lampe_ancienne_on_off
    domain: switch
  mode: single
- id: '1688076926078'
  alias: Associate switch.2buttons-"prise ventilateur"
  description: Pressing switch.2buttons (button 2) toggles prise ventilateur.
  trigger:
  - device_id: 3ab9c428743d0b8a5c6a42a425ec26d7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - type: toggle
    device_id: 57d06ece0d720e540cf89f953a317a44
    entity_id: switch.prise_ventilateur_on_off
    domain: switch
  mode: single
- id: '1711271735265'
  alias: Notificação se fumaça
  description: ''
  trigger:
  - type: smoke
    platform: device
    device_id: dbefe97d57c39d2a3af0c4bc082a16ec
    entity_id: e97ad31699d24775150ed51ad50f4031
    domain: binary_sensor
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      title: Alerta fumaça
      message: Fumaça detectada na cozinha
  mode: single
- id: '1711275724234'
  alias: Notifier si chauffe-serviettes allumé
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 45d4c955aff7e541b11bf5592ddd5c8f
    entity_id: 2a1e6f1dca7121efde8452ef29a371d3
    domain: sensor
    above: 100
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: Chauffe-serviettes sdb haut allumé !
      title: Alerte consommation
  mode: single
- id: '1711276410787'
  alias: Notifier chauffe-serviettes sdb haut éteint
  description: Chauffe-serviettes sdb haut éteint.
  trigger:
  - type: power
    platform: device
    device_id: 45d4c955aff7e541b11bf5592ddd5c8f
    entity_id: 2a1e6f1dca7121efde8452ef29a371d3
    domain: sensor
    below: 100
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: Chauffe-serviettes sdb haut éteint.
      title: Info consommation
  mode: single
